---
params:
  figure: "Extended Data Fig. 5A"
  response_variable: "SPW Rate"
title: "`r params$response_variable` during first novel object exposure in Novelty vs Dual experiments (`r params$figure`)"
---
\pagenumbering{gobble}
```{r, include=FALSE, eval=FALSE} 
# For debugging only. Will not run when knit.
params <- list()
params$response_variable <- "SPW Rate"
```
```{r, include=FALSE}
library(here)
source(here("analysis", "seahorse.R"))

# Using unbalanced data (subjects from both Novelty and Dual experiments)
unb <- list()
unb$data <-
  sh$load_measures_for_first_novelty_testing(only_dual_subjects = FALSE)
unb$models <-
  sh$fit_basic_models(
    unb$data, params$response_variable, "experiment", "subject"
  )
unb$anova <- anova(unb$models$full, unb$models$null)
unb$sig <- sh$get_anova_pval(unb$anova) < sh$alpha
if (unb$sig) {
  # Effect size for main effect of experiment.
  unb$eff_size <-
    sh$fit_models_for_cohens_fsquared(
      unb$data, unb$models$full, unb$models$null
    )
  unb$eff_size$fsquared <-
    sh$cohens_local_fsquared(unb$eff_size$models$a, unb$eff_size$models$b)
  unb$effect_size_msg <- paste(
    "Cohen's local f^2 analogue for main effect:",
    format(round(unb$eff_size$fsquared, 3), nsmall = 3)
  )
  # Difference between experiments, with confidence interval.
  unb$diff <- fixef(unb$models$full)[["experimentDual"]]
  unb$ci <- confint(glht(unb$models$full, rbind("Dual - Novelty" = c(0, 1))))
}

# Using balanced data (only subjects with both Novelty and Dual experiments)
bal <- list()
bal$data <-
  sh$load_measures_for_first_novelty_testing(only_dual_subjects = TRUE)
bal$models <-
  sh$fit_basic_models(
    bal$data, params$response_variable, "experiment", "subject"
  )
bal$anova <- anova(bal$models$full, bal$models$null)
bal$sig <- sh$get_anova_pval(bal$anova) < sh$alpha
if (bal$sig) {
  # Effect size for main effect of experiment.
  bal$eff_size <-
    sh$fit_models_for_cohens_fsquared(
      bal$data, bal$models$full, bal$models$null
    )
  bal$eff_size$fsquared <-
    sh$cohens_local_fsquared(bal$eff_size$models$a, bal$eff_size$models$b)
  bal$effect_size_msg <- paste(
    "Cohen's local f^2 analogue for main effect:",
    format(round(bal$eff_size$fsquared, 3), nsmall = 3)
  )
  # Difference between experiments, with confidence interval.
  bal$diff <- fixef(bal$models$full)[["experimentDual"]]
  bal$ci <- confint(glht(bal$models$full, rbind("Dual - Novelty" = c(0, 1))))
}
```
```{r}
# Unbalanced data: all subjects with either Novelty or Dual experiments.
# Left panel of each facet.
print(unb$anova) # Test for main effect of experiment.
```
```{r, eval=unb$sig}
print(unb$effect_size_msg) # Effect size
print(unb$ci) # Difference between experiments, with confidence interval.
```
```{r}
# Balanced data: only subjects with both Novelty and Dual experiments.
# Right panel of each facet.
print(bal$anova) # Test for main effect of experiment.
```
```{r, eval=bal$sig}
print(bal$effect_size_msg) # Effect size
print(bal$ci) # Difference between experiments, with confidence interval.
```
