---
title: 'Slow-to-fast gamma ratio (Fig. 4C)'
output: pdf_document
---
\pagenumbering{gobble}
```{r, include=FALSE}
library(arrow)
library(lme4)
library(multcomp)
library(here)
source(here("analysis", "seahorse.R"))

dat <- sh$load_sgfg_by_epoch_type()
models <- sh$fit_nested_models(
  dat, "Slow:Fast Gamma", "Epoch Type", "Experiment", "Subject"
)
```
```{r}
anova(models$full, models$reduced) # Test for interaction
anova(models$reduced, models$null) # Test for overall effect
```
```{r, include=FALSE}
effect_size <-
  sh$fit_models_for_cohens_fsquared(dat, models$reduced, models$null)
effect_size$fsquared <-
  sh$cohens_local_fsquared(effect_size$models$a, effect_size$models$b)
main_effect_effect_size_msg <- paste(
  "Cohen's local f^2 analogue for main effect:",
  format(round(effect_size$fsquared, 3), nsmall = 3)
)
```
```{r}
print(main_effect_effect_size_msg)
```
```{r, include=FALSE}
# Post-hoc tests, confidence intervals, and effect sizes
sgfg_contrast_matrix <- rbind(
  "No-SPW Wake - SPW Wake" = c(0, 1, 0, 0, 0, 0),
  "SPW NREM - SPW Wake" = c(0, 0, 1, 0, 0, 0),
  "SPW NREM - No-SPW Wake" = c(0, -1, 1, 0, 0, 0)
)

ph <- list()
ph$glht <- glht(models$reduced, sgfg_contrast_matrix)
ph$ci <- confint(ph$glht)
ph$effect_size <- sh$cohens_d_analogue(ph$glht, models$reduced)

pst_msg <- sh$format_posthoc_summary(ph)
```
```{r}
cat(pst_msg, sep = "\n") # Post-hoc tests for condition differences
```
