---
title: "Sleep period stage occupancy (Extended Data Figs. 2A, 2B)"
output: pdf_document
---
```{r, include = FALSE}
library(here)
source(here("analysis", "seahorse.R"))

bsl <- sh$test_single_day_occupancy("Baseline")
rec <- sh$test_single_day_occupancy("Recovery")
nod <- sh$test_single_experiment_occupancy("Novelty")
cow <- sh$test_single_experiment_occupancy("Locomotion")

rec_intractn_effect_size_msg <- paste(
  "Cohen's local f^2 analogue for interaction:",
  format(round(rec$interaction$effect_size$fsquared, 3), nsmall = 3)
)
rec_msg <- sh$format_posthoc_summary(rec$interaction$posthoc)

nod_intractn_effect_size_msg <- paste(
  "Cohen's local f^2 analogue for interaction:",
  format(round(nod$interaction$effect_size$fsquared, 3), nsmall = 3)
)
nod_msg <- sh$format_posthoc_summary(nod$interaction$posthoc)

cow_intractn_effect_size_msg <- paste(
  "Cohen's local f^2 analogue for interaction:",
  format(round(cow$interaction$effect_size$fsquared, 3), nsmall = 3)
)
cow_msg <- sh$format_posthoc_summary(cow$interaction$posthoc)
```

```{r}
# Extended Data Fig. 2A, left
print(bsl$interaction$anova) # Test for experiment * state interaction
print(bsl$main_effect$anova) # Test for main effect of experiment
```

```{r}
# Extended Data Fig. 2A, right
print(rec$interaction$anova) # Test for experiment * state interaction
print(rec_intractn_effect_size_msg)
cat(rec_msg, sep = "\n") # Post-hoc tests
```

```{r}
# Extended Data Fig. 2B, left
print(nod$interaction$anova) # Test for day * state interaction
print(nod_intractn_effect_size_msg)
cat(nod_msg, sep = "\n") # Post-hoc tests
```

```{r}
# Extended Data Fig. 2B, right
print(cow$interaction$anova) # Test for day * state interaction
print(cow_intractn_effect_size_msg)
cat(cow_msg, sep = "\n") # Post-hoc tests
```

```{r, include = FALSE}
# Supplementary Table 1
dat <- sh$load_rec_rem_vs_ewk_tdr_data()
models <- sh$fit_nested_models(
  dat, "REM fraction", "Total Hippocampal Theta:Delta", "Experiment", "Subject"
)
interaction <-
  sh$test_interaction(dat, models, sh$correlation_interaction_matrix)
assert_that(interaction$pval >= sh$alpha)
main_effect <- sh$test_main_effect(dat, models)
assert_that(main_effect$pval >= sh$alpha)
```

```{r}
# Supplementary Table 1 (No associated figure)
# "REM fraction vs. Extended wake theta:delta"
print(interaction$anova) # Test for interaction
print(main_effect$anova) # Test for main effect
```

