---
params:
  title: 'Wake vs. NREM ripple frequency (Supplementary Fig. 5)'
  fstem: 'SuppFig5'
title: "`r params$title`"
---
```{r}
#| include: false
library(devtools)
library(assertthat)
devtools::load_all()

dat <- load_ripple_frequency_data()
models <- fit_nested_models(
    dat, "Ripple.Frequency", "state", "experiment", "subject"
)

novelty_matrix <-
    rbind("Wake - NREM" = c(0, -1, 0, 0, 0, 0))
locomotion_matrix <-
    rbind("Wake - NREM" = c(0, -1, 0, -1, 0, 0))
dual_matrix <-
    rbind("Wake - NREM" = c(0, -1, 0, 0, 0, -1))

interaction <- test_interaction_with_experiment(
    dat, models, novelty_matrix, locomotion_matrix, dual_matrix
)
sig_interaction <- interaction$pval < 0.05

assertthat::assert_that(sig_interaction, msg = "Interaction is not significant")
interaction_effect_size_msg <- paste(
    "Cohen's local f^2 analogue for interaction:",
    format(round(interaction$effect_size$fsquared, 3), nsmall = 3)
)
nod_msg <- format_posthoc_summary(interaction$posthoc$nod)
cow_msg <- format_posthoc_summary(interaction$posthoc$cow)
ctn_msg <- format_posthoc_summary(interaction$posthoc$ctn)
```

```{r}
print(interaction$anova) # Test for interaction between state and experiment.
print(interaction_effect_size_msg)
cat(nod_msg, sep = "\n") # Post-hoc tests for Novelty.
cat(cow_msg, sep = "\n") # Post-hoc tests for Locomotion.
cat(ctn_msg, sep = "\n") # Post-hoc tests for Dual.
```